import type { ExpenseRecord, VendorContractor, ConstructionMilestone } from '@/types/expense.types'

export const MONTHLY_SPEND_DATA = [
  { month: 'Nov', spent: 65000, target: 80000 },
  { month: 'Dec', spent: 90000, target: 95000 },
  { month: 'Jan', spent: 120000, target: 110000 },
  { month: 'Feb', spent: 140000, target: 135000 },
  { month: 'Mar', spent: 155000, target: 150000 },
  { month: 'Apr', spent: 175000, target: 170000 },
  { month: 'May', spent: 185000, target: 180000 },
  { month: 'Jun', spent: 195000, target: 190000 },
  { month: 'Jul', spent: 200000, target: 205000 },
  { month: 'Aug', spent: 210000, target: 215000 },
  { month: 'Sep', spent: 198000, target: 195000 },
  { month: 'Oct', spent: 142000, target: 150000 },
]

export const CATEGORY_EXPENSES = [
  { name: 'Foundation & Civil', percentage: 36, amount: 675000, color: '#4f46e5' },
  { name: 'Steel & Reinforcement', percentage: 22, amount: 412500, color: '#3b82f6' },
  { name: 'Electrical Wiring', percentage: 14, amount: 262500, color: '#d97706' },
  { name: 'Plumbing & Piping', percentage: 12, amount: 225000, color: '#059669' },
  { name: 'Painting & Finishing', percentage: 9, amount: 168750, color: '#854d0e' },
  { name: 'Permits & Misc', percentage: 7, amount: 131250, color: '#64748b' },
]

export const KEY_CONTRACTORS: VendorContractor[] = [
  {
    id: 'vc-1',
    name: 'ABC Constructions',
    initials: 'AB',
    specialty: 'Civil Works & Structural Framing',
    totalPaid: 450000,
    contractsCount: 3,
    invoicesCount: 12,
    progressPercentage: 92,
    status: 'in_progress',
  },
  {
    id: 'vc-2',
    name: 'Steel World Ltd.',
    initials: 'SW',
    specialty: 'Materials & TMT 550D Rebars',
    totalPaid: 320000,
    contractsCount: 2,
    invoicesCount: 4,
    progressPercentage: 100,
    status: 'settled',
  },
  {
    id: 'vc-3',
    name: 'Rahul Electrician',
    initials: 'RE',
    specialty: 'Concealed Conduit & Wiring',
    totalPaid: 82000,
    contractsCount: 1,
    invoicesCount: 3,
    progressPercentage: 65,
    status: 'in_progress',
  },
  {
    id: 'vc-4',
    name: 'Apex ReadyMix',
    initials: 'AR',
    specialty: 'Slab Pouring M25 Grade Mix',
    totalPaid: 165000,
    contractsCount: 2,
    invoicesCount: 2,
    progressPercentage: 100,
    status: 'completed',
  },
]

export const RECENT_EXPENSES: ExpenseRecord[] = [
  {
    id: 'exp-1',
    date: '2024-10-24',
    category: 'Electrical',
    categoryCode: 'ELEC',
    vendor: 'Rahul Electrician',
    paymentMethod: 'UPI • HDFC 8841',
    amount: 18500,
    status: 'paid',
  },
  {
    id: 'exp-2',
    date: '2024-10-21',
    category: 'Steel TMT',
    categoryCode: 'STEEL',
    vendor: 'Steel World Ltd.',
    paymentMethod: 'NEFT Transfer',
    amount: 120000,
    status: 'paid',
  },
  {
    id: 'exp-3',
    date: '2024-10-18',
    category: 'Plumbing',
    categoryCode: 'PLUMB',
    vendor: 'Supreme Pipes Hub',
    paymentMethod: 'Cheque #4091',
    amount: 34200,
    status: 'paid',
  },
  {
    id: 'exp-4',
    date: '2024-10-15',
    category: 'Civil Slab',
    categoryCode: 'CIVIL',
    vendor: 'ABC Constructions',
    paymentMethod: 'RTGS Settlement',
    amount: 250000,
    status: 'paid',
  },
  {
    id: 'exp-5',
    date: '2024-10-12',
    category: 'Permits',
    categoryCode: 'PERMIT',
    vendor: 'Municipal Corp Duty',
    paymentMethod: 'Net Banking',
    amount: 14800,
    status: 'paid',
  },
  {
    id: 'exp-6',
    date: '2024-10-08',
    category: 'Painting',
    categoryCode: 'PAINT',
    vendor: 'Asian Paints Dealer',
    paymentMethod: 'Corp Credit Card',
    amount: 28400,
    status: 'paid',
  },
]

export const CONSTRUCTION_MILESTONES: ConstructionMilestone[] = [
  {
    id: 'ms-1',
    title: 'Foundation Pouring',
    badgeText: 'Batch #4 Inspected',
    badgeVariant: 'success',
    verificationDate: 'Verified 22 Oct 2024',
    note: 'Slab casting test cubes passed 28-day compression benchmark at 27.4 N/mm².',
    imageUrl: 'https://images.unsplash.com/photo-1541888946425-d0fbb186c5f8?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 'ms-2',
    title: 'Structural Steel Delivery',
    badgeText: '8.2 Tonnes Received',
    badgeVariant: 'primary',
    verificationDate: 'Delivery Slip #TMT-994',
    note: 'Direct shipment from Steel World. Weight verified on weighbridge slip #1042.',
    imageUrl: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 'ms-3',
    title: 'Conduit & Plumbing Rough-In',
    badgeText: '75% Conduits Laid',
    badgeVariant: 'warning',
    verificationDate: 'MEP Phase 1 Signoff',
    note: 'Pressure test passed at 10 Bar for 4 hours without pressure drop.',
    imageUrl: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=600&auto=format&fit=crop&q=80',
  },
]
